"""The ordered curriculum. One problem per day. Day numbers come from list order."""
from dataclasses import dataclass

TESTS_MARKER = "# ==== TESTS (do not edit below this line) ===="


@dataclass(frozen=True)
class Day:
    n: int
    slug: str
    title: str
    module: str
    pattern: str
    target: str
    concepts: tuple
    kind: str = "code"  # "code" -> python file with tests, "written" -> markdown reviewed by Claude
    lc: int = None
    lc_slug: str = None
    difficulty: str = None

    @property
    def filename(self):
        return f"day{self.n:02d}_{self.slug}.{'py' if self.kind == 'code' else 'md'}"

    @property
    def url(self):
        return f"https://leetcode.com/problems/{self.lc_slug}/" if self.lc_slug else None


def lc(num, lc_slug, difficulty):
    return dict(lc=num, lc_slug=lc_slug, difficulty=difficulty)


M1 = "1. Hashing & Arrays"
M2 = "2. Two Pointers & Sliding Window"
M3 = "3. Binary Search"
M4 = "4. Linked Lists & Caches"
M5 = "5. Heaps & Scheduling"
M6 = "6. Stacks & Parsing"
M7 = "7. Intervals"
M8 = "8. Trees"
M9 = "9. Backtracking"
M10 = "10. Tries"
M11 = "11. Graphs"
M12 = "12. Dynamic Programming & Greedy"
M13 = "13. Rate Limiting & Streams"
M14 = "14. Concurrency"
M15 = "15. Mock Interviews"
M16 = "16. System Design"
M17 = "17. Behavioral & Readiness"

_SPECS = [
    # ---- 1. Hashing & Arrays ----
    dict(slug="two_sum", title="Two Sum", module=M1, pattern="Hash map (complement lookup)",
         target="O(n) time, O(n) space", **lc(1, "two-sum", "Easy"),
         concepts=("Hash map average O(1) get/put vs balanced BST O(log n) — and when ordering makes a tree worth it",
                   "Hash collisions, load factor, resizing: why O(1) is *amortized average*, worst case O(n)",
                   "Trading space for time: brute force O(n^2)/O(1) vs one-pass map O(n)/O(n)",
                   "One-pass trick: check for the complement before inserting the current element")),
    dict(slug="group_anagrams", title="Group Anagrams", module=M1, pattern="Hash map with canonical key",
         target="O(n*k) time, O(n*k) space (k = max word length)", **lc(49, "group-anagrams", "Medium"),
         concepts=("Canonical keys: map many equivalent inputs to one hashable key",
                   "Sorted-string key O(k log k) vs 26-count tuple key O(k)",
                   "Only immutable values are hashable in Python (tuple yes, list no)",
                   "defaultdict(list) for grouping")),
    dict(slug="product_except_self", title="Product of Array Except Self", module=M1, pattern="Prefix / suffix products",
         target="O(n) time, O(1) extra space (output array doesn't count), no division", **lc(238, "product-of-array-except-self", "Medium"),
         concepts=("Prefix and suffix accumulation: answer[i] = prefix(i) * suffix(i)",
                   "Why division fails (zeros) and is disallowed",
                   "Reusing the output array to get O(1) extra space",
                   "Two passes: left-to-right then right-to-left")),
    dict(slug="subarray_sum_k", title="Subarray Sum Equals K", module=M1, pattern="Prefix sum + hash map",
         target="O(n) time, O(n) space", **lc(560, "subarray-sum-equals-k", "Medium"),
         concepts=("Prefix sums: sum(i..j) = prefix[j+1] - prefix[i]",
                   "Counting pairs of prefixes with difference k using a map of prefix -> count",
                   "Why sliding window fails with negative numbers",
                   "Seeding the map with {0: 1}")),
    dict(slug="logger_rate_limiter", title="Logger Rate Limiter", module=M1, pattern="Hash map of last-seen timestamps",
         target="O(1) per call; bounded memory is the follow-up", **lc(359, "logger-rate-limiter", "Easy"),
         concepts=("Map message -> next allowed timestamp",
                   "Unbounded growth: a map that never evicts is a memory leak in production",
                   "Eviction options: periodic sweep, queue of (time, msg), two-bucket rotation",
                   "Monotonic timestamps assumption and what breaks if clocks go backwards")),
    # ---- 2. Two Pointers & Sliding Window ----
    dict(slug="three_sum", title="3Sum", module=M2, pattern="Sort + two pointers",
         target="O(n^2) time, O(1) extra space (ignoring sort/output)", **lc(15, "3sum", "Medium"),
         concepts=("Sorting unlocks two pointers: move left/right based on sum vs target",
                   "Reducing k-sum to (k-1)-sum by fixing one element",
                   "Skipping duplicates at every level to avoid duplicate triplets",
                   "Why O(n^2) is optimal-ish here and O(n^3) brute force is not acceptable")),
    dict(slug="container_most_water", title="Container With Most Water", module=M2, pattern="Converging two pointers (greedy)",
         target="O(n) time, O(1) space", **lc(11, "container-with-most-water", "Medium"),
         concepts=("Area = min(h[l], h[r]) * (r - l)",
                   "Greedy proof: moving the taller wall can never increase area, so move the shorter one",
                   "Converging pointers as pruning of the O(n^2) pair space")),
    dict(slug="longest_substring_no_repeat", title="Longest Substring Without Repeating Characters", module=M2,
         pattern="Variable sliding window + hash map", target="O(n) time, O(min(n, alphabet)) space",
         **lc(3, "longest-substring-without-repeating-characters", "Medium"),
         concepts=("Sliding window template: expand right, shrink left while invalid, record best",
                   "Jumping left pointer using last-seen index map (never move left backwards)",
                   "Each index enters/leaves window once -> O(n)",
                   "Streaming view: the window is a bounded buffer over an unbounded stream")),
    dict(slug="fruit_into_baskets", title="Fruit Into Baskets", module=M2, pattern="Sliding window with at-most-K distinct",
         target="O(n) time, O(1) space", **lc(904, "fruit-into-baskets", "Medium"),
         concepts=("Recognize 'longest subarray with at most K distinct values'",
                   "Window state as a count map; delete keys when count hits 0",
                   "Generalizing K=2 to any K")),
    dict(slug="min_window_substring", title="Minimum Window Substring", module=M2, pattern="Sliding window with need/have counters",
         target="O(m + n) time, O(alphabet) space", **lc(76, "minimum-window-substring", "Hard"),
         concepts=("Minimum-window template: expand until valid, then shrink while still valid",
                   "Track 'formed' count of satisfied characters to check validity in O(1)",
                   "Recording the best window as (start, length), not slicing each time")),
    # ---- 3. Binary Search ----
    dict(slug="binary_search", title="Binary Search", module=M3, pattern="Classic binary search",
         target="O(log n) time, O(1) space", **lc(704, "binary-search", "Easy"),
         concepts=("Invariant-driven binary search: define what lo/hi mean and keep it true",
                   "Closed [lo, hi] vs half-open [lo, hi) loops and their exit conditions",
                   "mid = lo + (hi - lo) // 2 (overflow habit from Java/C)",
                   "Lower bound / upper bound variants (bisect_left, bisect_right)")),
    dict(slug="search_rotated", title="Search in Rotated Sorted Array", module=M3, pattern="Binary search on the sorted half",
         target="O(log n) time, O(1) space", **lc(33, "search-in-rotated-sorted-array", "Medium"),
         concepts=("At any mid, one half is sorted — decide which by comparing to lo",
                   "Check if target lies within the sorted half's range, else go to the other half",
                   "Edge cases: single element, no rotation")),
    dict(slug="koko_bananas", title="Koko Eating Bananas", module=M3, pattern="Binary search on the answer",
         target="O(n log m) time (m = max pile), O(1) space", **lc(875, "koko-eating-bananas", "Medium"),
         concepts=("Binary search over a monotonic predicate, not an array",
                   "Find smallest k where feasible(k) is True",
                   "Ceiling division without floats: (p + k - 1) // k",
                   "Real use: capacity planning / minimum throughput searches")),
    dict(slug="time_map", title="Time Based Key-Value Store", module=M3, pattern="Hash map + binary search floor",
         target="set O(1), get O(log n), O(n) space", **lc(981, "time-based-key-value-store", "Medium"),
         concepts=("Versioned storage: key -> append-only list of (timestamp, value)",
                   "Timestamps strictly increase per key, so the list stays sorted for free",
                   "Floor search: largest timestamp <= query (bisect_right - 1)",
                   "Production analogs: MVCC, time-series stores, config history")),
    # ---- 4. Linked Lists & Caches ----
    dict(slug="reverse_linked_list", title="Reverse Linked List", module=M4, pattern="Pointer manipulation",
         target="O(n) time, O(1) space (iterative)", **lc(206, "reverse-linked-list", "Easy"),
         concepts=("prev/curr/next three-pointer iteration",
                   "Recursive version and why it costs O(n) stack",
                   "Draw the pointers before coding")),
    dict(slug="merge_two_lists", title="Merge Two Sorted Lists", module=M4, pattern="Dummy head + tail pointer",
         target="O(n + m) time, O(1) space", **lc(21, "merge-two-sorted-lists", "Easy"),
         concepts=("Sentinel/dummy node removes empty-list special cases",
                   "Splicing existing nodes instead of allocating new ones",
                   "This is the merge step of merge sort and of k-way log merging")),
    dict(slug="lru_cache", title="LRU Cache", module=M4, pattern="Hash map + doubly linked list",
         target="get O(1), put O(1)", **lc(146, "lru-cache", "Medium"),
         concepts=("Map key -> node for O(1) lookup; DLL for O(1) recency reordering",
                   "Head/tail sentinel nodes remove boundary checks",
                   "Node stores its key so eviction can delete from the map",
                   "OrderedDict does this for you — know both, interviewers usually want the manual version",
                   "TTL extension: store expiry per node, check on get")),
    dict(slug="lfu_cache", title="LFU Cache", module=M4, pattern="Frequency buckets of ordered sets + min-freq pointer",
         target="get O(1), put O(1)", **lc(460, "lfu-cache", "Hard"),
         concepts=("Two maps: key -> (value, freq) and freq -> ordered keys (LRU tiebreak within a freq)",
                   "min_freq pointer: only ever increments by 1 on touch, resets to 1 on insert",
                   "Why a heap would be O(log n) and is not acceptable",
                   "LFU vs LRU trade-offs: frequency pollution from old hot keys")),
    # ---- 5. Heaps & Scheduling ----
    dict(slug="kth_largest", title="Kth Largest Element in an Array", module=M5, pattern="Size-k min-heap (or quickselect)",
         target="O(n log k) time, O(k) space (quickselect: O(n) average)", **lc(215, "kth-largest-element-in-an-array", "Medium"),
         concepts=("Binary heap: push/pop O(log n), peek O(1), heapify O(n)",
                   "Python heapq is a min-heap; negate for max-heap",
                   "Keep a min-heap of size k — its root is the kth largest",
                   "Quickselect: O(n) average, O(n^2) worst; randomize the pivot")),
    dict(slug="top_k_frequent", title="Top K Frequent Elements", module=M5, pattern="Count + heap or bucket sort",
         target="O(n log k) with heap, or O(n) with bucket sort", **lc(347, "top-k-frequent-elements", "Medium"),
         concepts=("Counter to get frequencies",
                   "Heap of size k over (freq, value)",
                   "Bucket sort by frequency: index = count, max index = n",
                   "Heavy-hitters at scale: Count-Min Sketch as the streaming approximation")),
    dict(slug="merge_k_lists", title="Merge k Sorted Lists", module=M5, pattern="K-way merge with a heap",
         target="O(N log k) time, O(k) space", **lc(23, "merge-k-sorted-lists", "Hard"),
         concepts=("Heap holds one head per list; pop smallest, push its next",
                   "Tie-breaking: push (val, index, node) so nodes are never compared",
                   "Divide and conquer pairwise merge is also O(N log k)",
                   "Production: merging sorted log segments / SSTables / external sort")),
    dict(slug="find_median_stream", title="Find Median from Data Stream", module=M5, pattern="Two heaps",
         target="addNum O(log n), findMedian O(1)", **lc(295, "find-median-from-data-stream", "Hard"),
         concepts=("Max-heap for lower half, min-heap for upper half",
                   "Invariant: sizes differ by at most 1, every low <= every high",
                   "Rebalance after each insert",
                   "Streaming percentiles in practice: t-digest / HDR histograms")),
    dict(slug="task_scheduler", title="Task Scheduler", module=M5, pattern="Greedy counting (or max-heap + cooldown queue)",
         target="O(n) time, O(1) space (26 task types)", **lc(621, "task-scheduler", "Medium"),
         concepts=("The most frequent task dictates the frame: (max_count - 1) * (n + 1) + num_with_max",
                   "Answer is max(len(tasks), frame)",
                   "Simulation alternative: max-heap + queue of (ready_time, count)")),
    # ---- 6. Stacks & Parsing ----
    dict(slug="valid_parentheses", title="Valid Parentheses", module=M6, pattern="Stack",
         target="O(n) time, O(n) space", **lc(20, "valid-parentheses", "Easy"),
         concepts=("Stack for nested structure matching",
                   "Map closer -> opener",
                   "Fail fast on empty stack; succeed only if stack empty at end")),
    dict(slug="decode_string", title="Decode String", module=M6, pattern="Stack-based parser",
         target="O(output length) time and space", **lc(394, "decode-string", "Medium"),
         concepts=("Tokenizing: digits, letters, '[' and ']' as state transitions",
                   "Push (current_string, repeat_count) on '['; pop and combine on ']'",
                   "Multi-digit numbers",
                   "Recursive-descent alternative")),
    dict(slug="daily_temperatures", title="Daily Temperatures", module=M6, pattern="Monotonic decreasing stack",
         target="O(n) time, O(n) space", **lc(739, "daily-temperatures", "Medium"),
         concepts=("Monotonic stack: store indices of unresolved items",
                   "When a bigger value arrives, it resolves everything smaller on the stack",
                   "Each index is pushed and popped once -> O(n)",
                   "Next greater / next smaller element family")),
    dict(slug="largest_rectangle", title="Largest Rectangle in Histogram", module=M6, pattern="Monotonic increasing stack",
         target="O(n) time, O(n) space", **lc(84, "largest-rectangle-in-histogram", "Hard"),
         concepts=("For each bar, width extends to the nearest smaller bar on each side",
                   "Popping a bar means its right boundary is found; the new stack top is its left boundary",
                   "Sentinel 0 at the end flushes the stack")),
    dict(slug="uncommon_words", title="Uncommon Words from Two Sentences", module=M6, pattern="Tokenize + count",
         target="O(m + n) time and space", **lc(884, "uncommon-words-from-two-sentences", "Easy"),
         concepts=("Reframe: uncommon = appears exactly once across both sentences",
                   "str.split() tokenization and its whitespace behavior",
                   "Counter over the concatenated token stream")),
    dict(slug="text_justification", title="Text Justification", module=M6, pattern="Greedy line packing + careful formatting",
         target="O(total characters) time", **lc(68, "text-justification", "Hard"),
         concepts=("Greedy: pack as many words as fit (words + minimum single spaces <= width)",
                   "Distribute spaces: base = gaps // slots, extra go to the leftmost slots",
                   "Special cases: last line and single-word lines are left-justified",
                   "Write helper functions; boundary logic is the whole problem")),
    # ---- 7. Intervals ----
    dict(slug="merge_intervals", title="Merge Intervals", module=M7, pattern="Sort by start + sweep",
         target="O(n log n) time, O(n) space", **lc(56, "merge-intervals", "Medium"),
         concepts=("Sorting by start means overlaps can only happen with the last merged interval",
                   "Overlap test: next.start <= last.end (touching counts here)",
                   "Merged end = max(last.end, next.end) — a contained interval must not shrink it")),
    dict(slug="insert_interval", title="Insert Interval", module=M7, pattern="Three-phase linear scan",
         target="O(n) time, O(n) space", **lc(57, "insert-interval", "Medium"),
         concepts=("Input is already sorted: no need to sort again",
                   "Phase 1: intervals ending before new start; phase 2: merge overlaps; phase 3: rest",
                   "Why O(n) beats re-sorting")),
    dict(slug="meeting_rooms_ii", title="Meeting Rooms II", module=M7, pattern="Min-heap of end times (or sweep line)",
         target="O(n log n) time, O(n) space", **lc(253, "meeting-rooms-ii", "Medium"),
         concepts=("Max concurrent overlap = rooms needed",
                   "Sort by start; heap of end times; reuse a room if earliest end <= start",
                   "Sweep line alternative: sorted starts and ends with two pointers",
                   "Production: connection pool sizing, concurrent stream peaks")),
    # ---- 8. Trees ----
    dict(slug="invert_tree", title="Invert Binary Tree", module=M8, pattern="Recursive DFS",
         target="O(n) time, O(h) space", **lc(226, "invert-binary-tree", "Easy"),
         concepts=("Recursion template: base case, recurse on children, combine",
                   "O(h) stack: h = log n balanced, n skewed",
                   "Iterative version with an explicit stack/queue")),
    dict(slug="level_order", title="Binary Tree Level Order Traversal", module=M8, pattern="BFS with level sizing",
         target="O(n) time, O(w) space (w = max width)", **lc(102, "binary-tree-level-order-traversal", "Medium"),
         concepts=("collections.deque for O(1) popleft (list.pop(0) is O(n))",
                   "Snapshot len(queue) at the start of each level",
                   "BFS vs DFS memory profile: width vs height")),
    dict(slug="validate_bst", title="Validate Binary Search Tree", module=M8, pattern="DFS with bounds",
         target="O(n) time, O(h) space", **lc(98, "validate-binary-search-tree", "Medium"),
         concepts=("BST property is global, not just parent/child",
                   "Pass (low, high) bounds down the recursion",
                   "In-order traversal of a BST is strictly increasing — alternative check")),
    dict(slug="lca_binary_tree", title="Lowest Common Ancestor of a Binary Tree", module=M8, pattern="Post-order DFS returning found nodes",
         target="O(n) time, O(h) space", **lc(236, "lowest-common-ancestor-of-a-binary-tree", "Medium"),
         concepts=("Return value semantics: the node found in this subtree (p, q, or LCA) or None",
                   "If both children return non-None, current node is the LCA",
                   "BST variant is simpler: walk down by value")),
    dict(slug="serialize_tree", title="Serialize and Deserialize Binary Tree", module=M8, pattern="Pre-order with null markers",
         target="O(n) time and space for both", **lc(297, "serialize-and-deserialize-binary-tree", "Hard"),
         concepts=("Pre-order + explicit null markers uniquely encodes a tree",
                   "Deserialize with an iterator over tokens and recursion",
                   "Format design: delimiters, negative numbers, compactness — same concerns as wire formats")),
    # ---- 9. Backtracking ----
    dict(slug="subsets", title="Subsets", module=M9, pattern="Backtracking (choose / don't choose)",
         target="O(n * 2^n) time, O(n) recursion space", **lc(78, "subsets", "Medium"),
         concepts=("Decision tree: each element in or out -> 2^n leaves",
                   "Backtracking template: choose, recurse, un-choose",
                   "Copy the path when recording (path[:])",
                   "Bitmask enumeration alternative")),
    dict(slug="combination_sum", title="Combination Sum", module=M9, pattern="Backtracking with reuse + pruning",
         target="Exponential; prune with sorted candidates", **lc(39, "combination-sum", "Medium"),
         concepts=("Pass a start index to avoid permutations of the same combination",
                   "Reuse allowed: recurse with the same index",
                   "Sort + break early when candidate > remaining")),
    dict(slug="word_search", title="Word Search", module=M9, pattern="Grid DFS backtracking",
         target="O(m * n * 4^L) time, O(L) space", **lc(79, "word-search", "Medium"),
         concepts=("DFS from every cell; mark visited in-place and restore after",
                   "Bounds + mismatch checks as early exits",
                   "Pruning: character frequency check before searching")),
    # ---- 10. Tries ----
    dict(slug="implement_trie", title="Implement Trie (Prefix Tree)", module=M10, pattern="Trie",
         target="insert/search/startsWith O(L)", **lc(208, "implement-trie-prefix-tree", "Medium"),
         concepts=("Node = children map + end-of-word flag",
                   "O(L) per op independent of number of words",
                   "Uses: autocomplete, routing tables, prefix filters")),
    dict(slug="word_search_ii", title="Word Search II", module=M10, pattern="Trie + grid backtracking",
         target="O(m * n * 4^L) worst case, much less with pruning", **lc(212, "word-search-ii", "Hard"),
         concepts=("Build a trie of words; DFS the grid walking the trie in lockstep",
                   "Store the word at the terminal node to avoid rebuilding strings",
                   "Prune: remove found words / empty trie branches")),
    # ---- 11. Graphs ----
    dict(slug="number_of_islands", title="Number of Islands", module=M11, pattern="Grid DFS/BFS flood fill",
         target="O(m * n) time, O(m * n) space worst case", **lc(200, "number-of-islands", "Medium"),
         concepts=("Graph representations: adjacency list, matrix, implicit grid",
                   "Flood fill marks a whole component per outer-loop hit",
                   "Recursion depth limits in Python -> prefer iterative BFS for big grids")),
    dict(slug="clone_graph", title="Clone Graph", module=M11, pattern="DFS/BFS with old->new map",
         target="O(V + E) time and space", **lc(133, "clone-graph", "Medium"),
         concepts=("Visited map doubles as the old->new mapping",
                   "Create the clone before recursing into neighbors to handle cycles",
                   "Deep copy of any cyclic object graph uses this pattern")),
    dict(slug="rotting_oranges", title="Rotting Oranges", module=M11, pattern="Multi-source BFS",
         target="O(m * n) time and space", **lc(994, "rotting-oranges", "Medium"),
         concepts=("Seed the queue with all sources at time 0",
                   "BFS levels = minutes elapsed",
                   "Count fresh up front to detect unreachable (-1)")),
    dict(slug="course_schedule", title="Course Schedule", module=M11, pattern="Cycle detection via Kahn's algorithm",
         target="O(V + E) time and space", **lc(207, "course-schedule", "Medium"),
         concepts=("Build systems as DAGs: an edge means 'must happen before'",
                   "Kahn's: indegree array + queue of zero-indegree nodes",
                   "If processed count < V, there is a cycle",
                   "DFS three-color (white/gray/black) alternative")),
    dict(slug="course_schedule_ii", title="Course Schedule II", module=M11, pattern="Topological sort (Kahn's)",
         target="O(V + E) time and space", **lc(210, "course-schedule-ii", "Medium"),
         concepts=("The order nodes leave the queue IS a valid topological order",
                   "Multiple valid orders exist — tests must accept any",
                   "Return [] on cycle")),
    dict(slug="alien_dictionary", title="Alien Dictionary", module=M11, pattern="Graph construction + topo sort",
         target="O(C) time (C = total characters), O(1) space for 26 letters", **lc(269, "alien-dictionary", "Hard"),
         concepts=("Derive edges only from the FIRST differing character of adjacent words",
                   "Invalid input: a word followed by its own prefix (e.g. 'abc' before 'ab')",
                   "Include every letter as a node even with no edges",
                   "Cycle -> return empty string")),
    dict(slug="redundant_connection", title="Redundant Connection", module=M11, pattern="Union-Find",
         target="O(n * α(n)) time, O(n) space", **lc(684, "redundant-connection", "Medium"),
         concepts=("Disjoint set: find with path compression, union by rank/size",
                   "Adding an edge between already-connected nodes creates a cycle",
                   "α(n) inverse Ackermann ≈ constant",
                   "Uses: connectivity, Kruskal's MST, network partitions")),
    dict(slug="network_delay_time", title="Network Delay Time", module=M11, pattern="Dijkstra",
         target="O(E log V) time, O(V + E) space", **lc(743, "network-delay-time", "Medium"),
         concepts=("Dijkstra: min-heap of (dist, node); skip stale entries",
                   "Requires non-negative weights (Bellman-Ford otherwise)",
                   "Answer = max shortest distance; -1 if any node unreachable")),
    # ---- 12. DP & Greedy ----
    dict(slug="climbing_stairs", title="Climbing Stairs", module=M12, pattern="1-D DP",
         target="O(n) time, O(1) space", **lc(70, "climbing-stairs", "Easy"),
         concepts=("DP = recursion + memoization of overlapping subproblems",
                   "State, transition, base case: f(n) = f(n-1) + f(n-2)",
                   "Top-down (lru_cache) vs bottom-up; rolling variables for O(1) space")),
    dict(slug="house_robber", title="House Robber", module=M12, pattern="1-D DP with take/skip",
         target="O(n) time, O(1) space", **lc(198, "house-robber", "Medium"),
         concepts=("Transition: best(i) = max(best(i-1), best(i-2) + nums[i])",
                   "Take/skip decisions as the core DP shape",
                   "Circular variant (213): run twice excluding first or last")),
    dict(slug="coin_change", title="Coin Change", module=M12, pattern="Unbounded knapsack DP",
         target="O(amount * coins) time, O(amount) space", **lc(322, "coin-change", "Medium"),
         concepts=("dp[a] = min over coins of dp[a - c] + 1",
                   "Why greedy fails (coins [1,3,4], amount 6)",
                   "Infinity sentinel for unreachable amounts",
                   "BFS view: shortest path in amount-space")),
    dict(slug="longest_increasing_subsequence", title="Longest Increasing Subsequence", module=M12, pattern="Patience sorting (binary search) DP",
         target="O(n log n) time, O(n) space", **lc(300, "longest-increasing-subsequence", "Medium"),
         concepts=("O(n^2) DP: dp[i] = 1 + max(dp[j]) for j < i with nums[j] < nums[i]",
                   "tails[k] = smallest tail of an increasing subsequence of length k+1",
                   "bisect_left to replace; length of tails is the answer")),
    dict(slug="longest_common_subsequence", title="Longest Common Subsequence", module=M12, pattern="2-D DP",
         target="O(m * n) time, O(min(m, n)) space", **lc(1143, "longest-common-subsequence", "Medium"),
         concepts=("2-D table over prefixes: dp[i][j] for text1[:i], text2[:j]",
                   "Match -> diagonal + 1; else max(up, left)",
                   "Rolling rows to cut space",
                   "diff / version control is built on this")),
    dict(slug="word_break", title="Word Break", module=M12, pattern="DP over prefixes",
         target="O(n^2) time (n * max word len with the length cap), O(n) space", **lc(139, "word-break", "Medium"),
         concepts=("dp[i] = True if s[:i] can be segmented",
                   "Set lookup for dictionary words",
                   "Cap inner loop at max word length")),
    dict(slug="jump_game", title="Jump Game", module=M12, pattern="Greedy reach",
         target="O(n) time, O(1) space", **lc(55, "jump-game", "Medium"),
         concepts=("Greedy: track the farthest reachable index",
                   "If i > farthest you are stuck",
                   "When greedy is provably correct vs when you need DP")),
    dict(slug="edit_distance", title="Edit Distance", module=M12, pattern="2-D DP",
         target="O(m * n) time, O(n) space", **lc(72, "edit-distance", "Medium"),
         concepts=("dp[i][j] = min edits to turn word1[:i] into word2[:j]",
                   "Insert / delete / replace map to left / up / diagonal",
                   "Base rows: converting to/from empty string")),
    # ---- 13. Rate Limiting & Streams ----
    dict(slug="token_bucket", title="Token Bucket Rate Limiter", module=M13, pattern="Lazy refill arithmetic",
         target="O(1) per call, O(1) space", difficulty="Medium",
         concepts=("Fixed window vs sliding log vs sliding window counter vs token bucket vs leaky bucket",
                   "Token bucket allows bursts up to capacity, then sustains refill rate",
                   "Lazy refill on each call: tokens = min(cap, tokens + elapsed * rate)",
                   "Inject a clock for testability (hexagonal: time is a port)")),
    dict(slug="hit_counter", title="Design Hit Counter", module=M13, pattern="Sliding window with a queue / ring buffer",
         target="hit O(1), getHits O(1) amortized; O(window) memory with ring buffer", **lc(362, "design-hit-counter", "Medium"),
         concepts=("Queue of timestamps: pop expired from the front",
                   "Ring buffer of 300 (time, count) slots for bounded memory under bursts",
                   "Sliding window counter as the memory-cheap approximation")),
    dict(slug="log_aggregation", title="Log Stream Aggregation", module=M13, pattern="Streaming parse + bucketed counters",
         target="O(lines) time, O(minutes + distinct codes) memory — never load the whole file", difficulty="Medium",
         concepts=("Stream line-by-line with a file iterator; never readlines() a multi-GB file",
                   "Regex parsing, skipping malformed lines",
                   "Truncate timestamps to minute buckets for windowed error rates",
                   "Top-K via Counter.most_common / heapq.nlargest")),
    # ---- 14. Concurrency ----
    dict(slug="print_in_order", title="Print in Order", module=M14, pattern="Events / barriers between threads",
         target="No busy-waiting; each thread blocks until its turn", **lc(1114, "print-in-order", "Easy"),
         concepts=("Race conditions, critical sections, happens-before",
                   "Python GIL: prevents parallel bytecode, NOT races between threads",
                   "threading.Event, Lock, Condition, Semaphore — what each is for",
                   "Java map: CountDownLatch, ReentrantLock, Condition, Semaphore")),
    dict(slug="foobar_alternately", title="Print FooBar Alternately", module=M14, pattern="Paired semaphores",
         target="Strict alternation, no busy-waiting", **lc(1115, "print-foobar-alternately", "Medium"),
         concepts=("Semaphores as permits: acquire decrements, release increments",
                   "Ping-pong: foo releases bar's semaphore and vice versa",
                   "Condition variable alternative: always wait in a while loop (spurious wakeups)")),
    dict(slug="bounded_blocking_queue", title="Design Bounded Blocking Queue", module=M14, pattern="Condition variables (producer-consumer)",
         target="enqueue/dequeue O(1), block instead of spin", **lc(1188, "design-bounded-blocking-queue", "Medium"),
         concepts=("Producer-consumer with two conditions: not_full and not_empty sharing one lock",
                   "while (not predicate): wait()  — never 'if'",
                   "Backpressure: bounded queues protect memory",
                   "Java: ArrayBlockingQueue / LinkedBlockingQueue")),
    dict(slug="thread_safe_lru", title="Thread-Safe LRU Cache", module=M14, pattern="Lock-guarded compound operations",
         target="get/put O(1) under a lock; no lost updates", difficulty="Medium",
         concepts=("Why an LRU get is a WRITE (it reorders recency) — read/write locks don't help as much as you'd think",
                   "Always release in finally / use 'with lock:'",
                   "Lock striping / sharding to cut contention",
                   "Java: ReentrantReadWriteLock, ConcurrentHashMap, Caffeine")),
    dict(slug="ring_buffer", title="Thread-Safe Ring Buffer", module=M14, pattern="Circular array with head/count",
         target="put/get O(1), fixed memory", difficulty="Medium",
         concepts=("Circular indexing: (head + count) % capacity",
                   "Full vs empty disambiguation (count field or one wasted slot)",
                   "Lock-based vs lock-free (CAS, LMAX Disruptor) trade-offs",
                   "Cache lines and false sharing (conceptual)")),
    dict(slug="web_crawler_mt", title="Web Crawler Multithreaded", module=M14, pattern="Thread pool + thread-safe visited set",
         target="Concurrent fetches; O(V + E) total work", **lc(1242, "web-crawler-multithreaded", "Medium"),
         concepts=("ThreadPoolExecutor and futures",
                   "Check-and-add to visited must be atomic (lock) to avoid duplicate work",
                   "Termination: track in-flight tasks, stop when none remain",
                   "I/O-bound work benefits from threads even with the GIL")),
    dict(slug="worker_pool", title="Worker Pool with Graceful Shutdown", module=M14, pattern="Threads + queue + poison pills",
         target="Submit O(1); shutdown drains queued work, then joins", difficulty="Medium",
         concepts=("Fixed pool of worker threads pulling from a shared queue",
                   "Graceful shutdown: stop accepting, drain, send one poison pill per worker, join",
                   "Error isolation: one failing task must not kill a worker",
                   "Java: ExecutorService.shutdown() vs shutdownNow(), awaitTermination")),
    dict(slug="mt_log_processor", title="Multithreaded Log Pipeline", module=M14, pattern="Producer -> workers -> aggregator pipeline",
         target="Correct totals under concurrency; bounded memory via bounded queue", difficulty="Medium",
         concepts=("Pipeline stages connected by bounded queues",
                   "Per-worker local counters merged at the end beat a shared locked counter",
                   "Sentinels to signal end-of-stream through each stage")),
    # ---- 15. Mock Interviews ----
    dict(slug="mock_lru", title="Mock: LRU Cache (40-minute timer)", module=M15, pattern="Live coding drill",
         target="get O(1), put O(1); finish in 40 minutes", **lc(146, "lru-cache", "Medium"),
         concepts=("Step 1 (5 min): clarify constraints out loud",
                   "Step 2 (5 min): brute force vs optimal, state complexities",
                   "Step 3 (20 min): write clean code",
                   "Step 4 (10 min): dry-run tests and edge cases")),
    dict(slug="mock_course_schedule_ii", title="Mock: Course Schedule II (narrated)", module=M15, pattern="Live coding drill",
         target="O(V + E) time and space; finish in 35 minutes", **lc(210, "course-schedule-ii", "Medium"),
         concepts=("Narrate trade-offs: Kahn's vs DFS, O(V + E) time/space",
                   "State assumptions about input validity",
                   "Test with a cycle, a disconnected graph, and zero prerequisites")),
    dict(slug="mock_randomized_set", title="Mock: Insert Delete GetRandom O(1) (unseen)", module=M15, pattern="Array + index map, swap-with-last delete",
         target="insert/remove/getRandom O(1) average", **lc(380, "insert-delete-getrandom-o1", "Medium"),
         concepts=("Cold problem: practice the 4-step communication drill",
                   "Combining structures to get each op's best complexity",
                   "Swap-with-last trick for O(1) array removal")),
    # ---- 16. System Design ----
    dict(slug="design_logging_metrics", title="Design a Distributed Logging & Metrics System", module=M16, kind="written",
         pattern="System design", target="45-minute design covering requirements -> API -> data -> scale -> failures", difficulty="Hard",
         concepts=("Framework: requirements, estimates, API, data model, high-level design, deep dives, trade-offs",
                   "Agents -> buffer (Kafka) -> stream processors -> hot store / cold store",
                   "At-least-once vs exactly-once; idempotency keys; transactional outbox",
                   "Cardinality explosion in metrics labels; downsampling and retention tiers")),
    dict(slug="design_event_streaming_sdk", title="Design a High-Throughput Event Streaming SDK", module=M16, kind="written",
         pattern="System design", target="Client SDK design: batching, retries, ordering, backpressure", difficulty="Hard",
         concepts=("Partitioning strategies: key hash, round robin, sticky; ordering is per partition",
                   "Batching + linger time vs latency; compression",
                   "Retries with backoff + jitter; idempotent producer; dead-letter queues",
                   "Backpressure: bounded in-memory buffer, block vs drop policies")),
    dict(slug="design_rate_limiter", title="Design a Distributed Rate Limiter", module=M16, kind="written",
         pattern="System design", target="Per-user/API limits across many gateway nodes", difficulty="Hard",
         concepts=("Algorithm choice revisited at scale (token bucket vs sliding window counter)",
                   "Centralized store (Redis + Lua atomic scripts) vs local limits with sync",
                   "Fail-open vs fail-closed when the limiter store is down",
                   "Headers: 429, Retry-After, X-RateLimit-Remaining")),
    dict(slug="design_video_streaming", title="Design a Video Streaming Platform", module=M16, kind="written",
         pattern="System design", target="Netflix-scale upload -> transcode -> CDN -> adaptive playback", difficulty="Hard",
         concepts=("Transcoding pipeline: chunking, parallel encode, multiple bitrates",
                   "Adaptive bitrate streaming (HLS/DASH) and manifests",
                   "CDN / Open Connect: pre-positioning popular content at the edge",
                   "Resilience: chaos engineering, regional failover, bulkheads, circuit breakers")),
    dict(slug="design_ttl_cache_integration", title="Architecture + Coding: TTL Cache in a Microservice", module=M16, kind="written",
         pattern="System design + coding", target="Explain where an in-process TTL cache fits and its failure modes", difficulty="Hard",
         concepts=("Cache-aside vs read-through vs write-through vs write-behind",
                   "In-process vs distributed cache (Redis): consistency, memory, cold starts",
                   "Stampede protection: request coalescing, jittered TTLs, stale-while-revalidate",
                   "Invalidation strategies and their consistency guarantees")),
    # ---- 17. Behavioral & Readiness ----
    dict(slug="story_architecture", title="STAR Story: Modernizing Core Architecture", module=M17, kind="written",
         pattern="Behavioral (STAR)", target="A 2-3 minute story with measurable results", difficulty="Medium",
         concepts=("STAR: Situation, Task, Action, Result — Action is ~60% of the story",
                   "Say 'I', not 'we', for your actions",
                   "Quantify results (latency, cost, loss rate, time saved)",
                   "Prepare follow-ups: what would you do differently?")),
    dict(slug="story_production_incident", title="STAR Story: Resolving a Major Production Issue", module=M17, kind="written",
         pattern="Behavioral (STAR)", target="A 2-3 minute story showing ownership and debugging method", difficulty="Medium",
         concepts=("Show your debugging method, not just the fix",
                   "Blameless framing; what you changed to prevent recurrence",
                   "Communication during the incident")),
    dict(slug="story_leadership", title="STAR Story: Leading Cross-Functional Technical Decisions", module=M17, kind="written",
         pattern="Behavioral (STAR)", target="A 2-3 minute story showing influence without authority", difficulty="Medium",
         concepts=("Influence without authority: data, prototypes, RFCs",
                   "Disagree and commit; handling pushback",
                   "Adoption metrics as results")),
    dict(slug="netflix_culture", title="Culture Fit: Freedom & Responsibility", module=M17, kind="written",
         pattern="Behavioral (values)", target="Stories mapped to candor, judgment, and context-not-control", difficulty="Medium",
         concepts=("Netflix culture memo: freedom & responsibility, context not control, keeper test",
                   "Candid feedback: a story of giving and receiving hard feedback",
                   "Judgment: a decision you made with incomplete information",
                   "Highly aligned, loosely coupled teams")),
    dict(slug="pattern_review", title="Final Polish: Pattern Recognition Sheet", module=M17, kind="written",
         pattern="Review", target="One-page sheet: signal -> pattern -> complexity for 15+ patterns", difficulty="Medium",
         concepts=("Problem signals -> pattern (e.g. 'sorted + target' -> two pointers / binary search)",
                   "Hash maps, sliding windows, heaps, monotonic stacks, graphs, DP, locks",
                   "Complexity of each pattern from memory")),
    dict(slug="application_readiness", title="Application Readiness", module=M17, kind="written",
         pattern="Career", target="Resume, LinkedIn, GitHub updated; target list written", difficulty="Easy",
         concepts=("Resume bullets: action + scope + measurable impact",
                   "Highlight AWS certification and enterprise platform projects",
                   "GitHub: pin 3-4 repos with clear READMEs",
                   "Target company list and referral plan")),
]

DAYS = tuple(Day(n=i + 1, **spec) for i, spec in enumerate(_SPECS))


def get(n):
    if not 1 <= n <= len(DAYS):
        raise ValueError(f"Day must be between 1 and {len(DAYS)}.")
    return DAYS[n - 1]
